#!/usr/bin/env python3
"""OSFilter kaynak dosyalarından deterministik filtre çıktıları üretir."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LISTS_DIR = ROOT / "lists"

SOURCES = {
    "Reklam": ROOT / "sources" / "ads.txt",
    "İzleyici": ROOT / "sources" / "trackers.txt",
    "Güvenlik": ROOT / "sources" / "security.txt",
    "Bahis/Kumar": ROOT / "sources" / "gambling.txt",
}

LABEL_RE = re.compile(r"^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$")


def normalize_domain(value: str) -> str:
    value = value.strip().rstrip(".").lower()
    if not value:
        raise ValueError("boş domain")
    if "://" in value or "/" in value or ":" in value or " " in value:
        raise ValueError(f"yalnızca alan adı bekleniyor: {value!r}")

    try:
        ascii_domain = value.encode("idna").decode("ascii")
    except UnicodeError as exc:
        raise ValueError(f"IDN dönüştürülemedi: {value!r}") from exc

    if len(ascii_domain) > 253:
        raise ValueError(f"domain çok uzun: {value!r}")

    labels = ascii_domain.split(".")
    if len(labels) < 2:
        raise ValueError(f"geçerli FQDN değil: {value!r}")
    if any(not LABEL_RE.fullmatch(label) for label in labels):
        raise ValueError(f"geçersiz domain etiketi: {value!r}")

    return ascii_domain


def load_domain_file(path: Path) -> list[str]:
    domains: list[str] = []
    if not path.exists():
        raise FileNotFoundError(path)

    for number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        try:
            domains.append(normalize_domain(line))
        except ValueError as exc:
            raise ValueError(f"{path.relative_to(ROOT)}:{number}: {exc}") from exc
    return domains


def unique_sorted(items) -> list[str]:
    return sorted(set(items))


def adblock_header(title: str, description: str) -> list[str]:
    return [
        "[Adblock Plus 2.0]",
        f"! Title: {title}",
        "! Homepage: https://github.com/osmanilcektu/osfilter",
        "! Expires: 12 hours",
        f"! Description: {description}",
        "! Maintainer: Osman İlçektuğ",
        "! Generated by scripts/build.py — do not edit generated outputs directly.",
        "",
    ]


def render_adblock(title: str, description: str, sections: list[tuple[str, list[str]]]) -> str:
    lines = adblock_header(title, description)
    for section_name, domains in sections:
        lines.append(f"! --- {section_name} ---")
        lines.extend(f"||{domain}^" for domain in domains)
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_hosts(domains: list[str]) -> str:
    header = [
        "# OSFilter hosts",
        "# Generated by scripts/build.py — do not edit directly.",
        "# Homepage: https://github.com/osmanilcektu/osfilter",
        "",
    ]
    return "\n".join(header + [f"0.0.0.0 {domain}" for domain in domains]).rstrip() + "\n"


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def main() -> None:
    allow = set(load_domain_file(ROOT / "allowlist.txt"))

    categories: dict[str, list[str]] = {}
    for name, path in SOURCES.items():
        categories[name] = unique_sorted(
            domain for domain in load_domain_file(path) if domain not in allow
        )

    full_sections = [(name, categories[name]) for name in SOURCES]
    full_domains = unique_sorted(
        domain for _, domains in full_sections for domain in domains
    )

    write(
        ROOT / "osfilter.txt",
        render_adblock(
            "OSFilter — Full",
            "Türkiye odaklı reklam, izleyici, güvenlik ve isteğe bağlı bahis/kumar alan adı filtresi.",
            full_sections,
        ),
    )
    write(ROOT / "hosts.txt", render_hosts(full_domains))

    write(
        LISTS_DIR / "osfilter-lite.txt",
        render_adblock(
            "OSFilter — Lite",
            "Reklam ve izleyici alan adları; güvenlik ve bahis kategorileri hariç.",
            [
                ("Reklam", categories["Reklam"]),
                ("İzleyici", categories["İzleyici"]),
            ],
        ),
    )
    write(
        LISTS_DIR / "osfilter-security.txt",
        render_adblock(
            "OSFilter — Security",
            "Doğrulanmış zararlı ve phishing alan adları.",
            [("Güvenlik", categories["Güvenlik"])],
        ),
    )
    write(
        LISTS_DIR / "osfilter-gambling.txt",
        render_adblock(
            "OSFilter — Gambling",
            "Türkiye odaklı bahis/kumar alan adları için ayrı kategori.",
            [("Bahis/Kumar", categories["Bahis/Kumar"])],
        ),
    )

    print(f"OSFilter üretildi: {len(full_domains)} benzersiz engellenen domain")


if __name__ == "__main__":
    main()
